=== ebikargar/Distributed-Programming-II/XMLSchemaexamples/networkExample/network.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/network/"
	targetNamespace="http://www.example.org/network/">
	<element name="network" type="tns:networkType">
		<key name="hostKey">
			<selector xpath="host"></selector>
			<field xpath="@id"></field>
		</key>

		<key name="groupKey">
			<selector xpath="group"></selector>
			<field xpath="@id"></field>
		</key>
		<keyref name="groupKeyRef" refer="tns:groupKey">
			<selector xpath="host"></selector>
			<field xpath="@group"></field>
		</keyref>

		<unique name="dummy1">
			<selector xpath="host/interface"></selector>
			<field xpath="@IP"></field>
		</unique>
		<unique name="dummy2">
			<selector xpath="host/interface"></selector>
			<field xpath="MAC"></field>
		</unique>
		<unique name="dummy3">
			<selector xpath="host/interface"></selector>
			<field xpath="name"></field>
		</unique>
	</element>

	<element name="description" type="string">
	</element>

	<complexType name="networkType">
		<sequence>
			<element name="group" maxOccurs="unbounded" minOccurs="0">
				<complexType>
					<sequence>
						<element ref="tns:description" maxOccurs="1" minOccurs="0"></element>
					</sequence>
					<attribute name="id" type="ID"></attribute>
				</complexType>
			</element>
			<element name="host" maxOccurs="unbounded" minOccurs="0">
				<complexType>
					<sequence>
						<element name="administrator" type="string"></element>
						<element ref="tns:description" maxOccurs="1" minOccurs="0"></element>
						<element name="interface" type="tns:interfaceType"
							maxOccurs="unbounded" minOccurs="1"></element>
							<element name="group" type="string" maxOccurs="unbounded"></element>
						</sequence>
					<attribute name="id" type="tns:hostnameType" use="required">
					</attribute>
					<attribute name="type" type="tns:hosttypeType"></attribute>
					<!-- <attribute name="groups" type="IDREFS"></attribute> -->
				</complexType>
			</element>
		</sequence>
	</complexType>

	<complexType name="interfaceType">
		<sequence>
			<element name="MAC" type="string"></element>
			<element name="name" type="string" maxOccurs="unbounded"
				minOccurs="1">
			</element>
		</sequence>
		<attribute name="IP" type="string"></attribute>
	</complexType>

	<simpleType name="hosttypeType">
		<restriction base="string">
			<enumeration value="computer"></enumeration>
			<enumeration value="stampante"></enumeration>
			<enumeration value="router"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="hostnameType">
		<restriction base="string">
			<pattern value="[A-Za-z0-9]*"></pattern>
			<maxLength value="6"></maxLength>
		</restriction>
	</simpleType>

</schema>

=== ebikargar/Distributed-Programming-II/XMLSchemaexamples/networkExample/network.xml
<?xml version="1.0"?>
<xr:network     
    xmlns:xr="http://www.example.org/network/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" 
    xsd:schemaLocation="http://www.example.org/network/ network.xsd">
	<host id="Host1">
		<administrator>administrator1</administrator>
		<interface IP="130.192.3.21">
			
			<MAC>00:01:02:03:04:05</MAC>
			<name>Host1</name>
		</interface>
	</host>
	<host id="Host2">
		<administrator>administrator1</administrator>
		<interface IP="130.192.3.22">
			<MAC>00:01:02:03:04:06</MAC>
			<name>Host2_i0</name>
		</interface>
		<interface IP="130.192.3.23">
			<MAC>00:01:02:03:04:07</MAC>
			<name>Host2_i1</name>
		</interface>
	</host>
</xr:network>
