=== ebikargar/Distributed-Programming-II/Assignment1a/dtd/nffgInfo.dtd
<!ELEMENT nffgVerifier (nffgSet)*>
<!ELEMENT nffgSet (nffg)+>
<!ELEMENT nffg (nodeSet*,linkSet*,policySet?)>
	<!ATTLIST nffg  
				nffgName 			ID 		#REQUIRED
				upTime				CDATA	#REQUIRED> <!-- do wee needed update time? -->
	<!ELEMENT nodeSet (node*)>
	<!ELEMENT node (providerCat*)>
	<!ATTLIST node 
		nodeName 		ID 		#REQUIRED>		
<!ELEMENT providerCat EMPTY>
	<!ATTLIST  providerCat
						funcType	(FW|DPI|NAT|SPAM|CACHE|VPN|WEB_SERVER|WEB_CLIENT|MAIL_SERVER|MAIL_CLIENT)	#REQUIRED>

<!ELEMENT linkSet (links*)>
<!ELEMENT links EMPTY>
	<!ATTLIST links
					linkName	ID 		#REQUIRED
					srcNode 	IDREF	#REQUIRED
					destNode	IDREF	#REQUIRED>
<!ELEMENT policySet (policy)*>
<!ELEMENT policy (providerCat*)>
	<!ATTLIST Policy
			policyName	   			ID 							#REQUIRED
			policyType				(reacheablility|travesal)	#REQUIRED
			verificationResult		(TRUE|FALSE)				#REQUIRED
			srcNode 				IDREF					 	#REQUIRED
			destNode				IDREF 						#REQUIRED>

=== ebikargar/Distributed-Programming-II/Assignment1a/dtd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nffgVerifier SYSTEM "nffgInfo.dtd" >
<nffgVerifier>
  <nffgSet>
    <nffg nffgName="idvalue0" upTime="">
      <nodeSet>
        <node nodeName="idvalue1">
          <providerCat funcType="FW"/>
        </node>
      </nodeSet>
      <linkSet>
        <links destNode="idvalue0" linkName="idvalue2" srcNode="idvalue0"/>
      </linkSet>
      <policySet>
        <policy>
          <providerCat funcType="FW"/>
        </policy>
      </policySet>
    </nffg>
  </nffgSet>
</nffgVerifier>
