=== ebikargar/Distributed-Programming-II/Assignment1a/xsd/nffgInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/nffgInfo" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://www.example.org/nffgInfo" elementFormDefault="qualified">

	<element name="nffgVerifier" type="tns:nffgVerifierType">
		<key name="policyNameKey">
			<selector xpath="tns:nffg/policy" />
			<field xpath="@policyName" />
		</key>
		<keyref name="policyNameRef" refer="tns:policyNameKey">
			<selector xpath="tns:nffg/policy"></selector>
			<field xpath="@policyName"></field>
		</keyref>
	</element>

	<complexType name="nffgVerifierType">
		<sequence>
			<element name="nffg" type="tns:nffgType" minOccurs="0"
				maxOccurs="unbounded">

				<key name="nffgNameKey">
					<selector xpath="tns:nffg" />
					<field xpath="@nffgName" />
				</key>
				<keyref name="nffgNameRef" refer="tns:nffgNameKey">
					<selector xpath="tns:nffg"></selector>
					<field xpath="@nffgName"></field>
				</keyref>
				<!-- nodeName and linksName is key inside nffg,is it correct? -->
				<key name="nodeNameKey">
					<selector xpath="tns:node" />
					<field xpath="@nodeName" />
				</key>
				<keyref name="nodeNameRef" refer="tns:nodeNameKey">
					<selector xpath="tns:node"></selector>
					<field xpath="@nodeName"></field>
				</keyref>

				<key name="linksNameKey">
					<selector xpath="tns:links" />
					<field xpath="@linkName" />
				</key>
				<keyref name="linksNameRef" refer="tns:linksNameKey">
					<selector xpath="tns:links"></selector>
					<field xpath="@linkName"></field>
				</keyref>
			</element>
		</sequence>
	</complexType>

	<complexType name="nffgType">
		<sequence>
			<element name="node" type="tns:nodeType" minOccurs="1"
				maxOccurs="unbounded"></element>
			<element name="links" type="tns:linksType" minOccurs="1"
				maxOccurs="unbounded"></element>
			<element name="policy" type="tns:policyType" minOccurs="1"
				maxOccurs="unbounded"></element>
			<element name="upTime" type="tns:timeType"></element>
		</sequence>
		<attribute name="nffgName" type="tns:myStringType" use="required" /><!-- 
			it's key inside nffg,do we need to define it here too?? -->
	</complexType>

	<complexType name="nodeType">
		<sequence>
			<element name="providerCat" type="tns:providerCatType"
				minOccurs="0" maxOccurs="unbounded"></element>
		</sequence> <!-- a general question:when we define an attribute as key/keyref,do we need 
			to define it as attribute too or no?what should be it's type then -->
		<attribute name="nodeName" type="tns:myStringType" use="required"></attribute>
		<attribute name="linkName" type="tns:myStringType" use="required"></attribute>
	</complexType>

	<complexType name="linksType">
		<attribute name="linkName" type="tns:myStringType" use="required" />
		<attribute name="srcNode" type="tns:myStringType" use="required" />
		<attribute name="destNode" type="tns:myStringType" use="required" />
	</complexType> <!-- key and keyref add on nffg element,correct? -->

	<complexType name="policyType">
		<sequence>
			<element name="traversComponent" type="tns:providerCatType"
				minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>  <!-- is it correct to define traversCoponent by this way? -->
		<attribute name="policyName" type="tns:myStringType" use="required"></attribute>
		<attribute name="nffgName" type="tns:myStringType" use="required"></attribute> <!-- what should be type of nffg here? to define reachability and trav? -->
		<attribute name="verificationResult" type="tns:resultType"
			use="required"></attribute> <!-- type should be positive|negative or true false,and for isPositive? -->
		<!-- define a simpletype by two enum -->
		<attribute name="isPositive" type="tns:resultType" use="required"></attribute>


		<attribute name="srcNode" type="tns:myStringType" use="required"></attribute> <!--do we need these two attr or no? -->
		<attribute name="destNode" type="tns:myStringType" use="required"></attribute>
	</complexType>

	<complexType name="timeType">
		<attribute name="hour" use="required">
			<simpleType>
				<restriction base="nonNegativeInteger">
					<maxInclusive value="24"></maxInclusive>
				</restriction>
			</simpleType>
		</attribute>

		<attribute name="minute" use="required">
			<simpleType>
				<restriction base="nonNegativeInteger">
					<maxInclusive value="59"></maxInclusive>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<simpleType name="myStringType">
		<restriction base="string">
			<pattern value="([a-zA-Z][a-zA-Z0-9]*)"></pattern> <!-- is it correct? -->
		</restriction>
	</simpleType>

	<complexType name="providerCatType">
		<attribute name="funcType" type="tns:funcType" use="required"></attribute>
	</complexType>
	<simpleType name="funcType">
		<restriction base="string">
			<enumeration value="FW"></enumeration>
			<enumeration value="DPI"></enumeration>
			<enumeration value="NAT"></enumeration>
			<enumeration value="SPAM"></enumeration>
			<enumeration value="CACHE"></enumeration>
			<enumeration value="VPN"></enumeration>
			<enumeration value="WEB_SERVER"></enumeration>
			<enumeration value="WEB_CLIENT"></enumeration>
			<enumeration value="MAIL_SERVER"></enumeration>
			<enumeration value="MAIL_CLIENT"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="resultType">
		<restriction base="string">
			<pattern value="positive|negative" />  <!-- msg,verification time should be added,should be positive-negative or true-false -->
		</restriction>
	</simpleType>
</schema>

=== ebikargar/Distributed-Programming-II/Assignment1b/xsd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:nffgVerifier xmlns:tns="http://www.example.org/nffgInfo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/nffgInfo nffgInfo.xsd ">
  <tns:nffg nffgName="">
    <tns:node linkName="" nodeName="">
      <tns:providerCat funcType="FW"/>
    </tns:node>
    <tns:links destNode="" linkName="" srcNode=""/>
    <tns:policy destNode="" isPositive="" nffgName="" policyName="" srcNode="" verificationResult="">
      <tns:traversComponent funcType="FW"/>
    </tns:policy>
    <tns:upTime hour="0" minute="0"/>
  </tns:nffg>
</tns:nffgVerifier>
